"""
Sentinel Proposals Models

Proposals are agent-generated suggestions for action.

Domain: Proposals
"""

from sqlalchemy import Column, String, Enum as SQLEnum, ForeignKey, Float, Text
from sqlalchemy.dialects.postgresql import UUID, JSONB
from sqlalchemy.orm import relationship

from db.session import Base
from db.models.base import TimestampMixin, UUIDPrimaryKey

import enum


class ProposalType(str, enum.Enum):
    """Types of proposals agents can generate."""
    
    CREATE_TASK = "create_task"
    CREATE_REMINDER = "create_reminder"
    SEND_EMAIL = "send_email"
    UPDATE_CALENDAR = "update_calendar"
    IGNORE = "ignore"


class ProposalStatus(str, enum.Enum):
    """Lifecycle status of a proposal."""
    
    PENDING = "pending"
    AWAITING_HUMAN = "awaiting_human"
    APPROVED = "approved"
    REJECTED = "rejected"
    EXECUTED = "executed"
    FAILED = "failed"


class Proposal(Base, UUIDPrimaryKey, TimestampMixin):
    """
    Represents an agent-generated suggestion.
    
    Proposals are:
    - Generated by agents
    - Never executed without approval
    - Traceable to observations
    - Evaluated by humans
    """
    
    __tablename__ = "proposals"
    
    proposal_type = Column(
        SQLEnum(ProposalType),
        nullable=False,
        index=True,
    )
    
    status = Column(
        SQLEnum(ProposalStatus),
        nullable=False,
        default=ProposalStatus.PENDING,
        index=True,
    )
    
    observation_id = Column(
        UUID(as_uuid=True),
        ForeignKey("observations.id", ondelete="CASCADE"),
        nullable=True,
        index=True,
        comment="Which observation triggered this proposal",
    )
    
    agent_name = Column(
        String(100),
        nullable=False,
        index=True,
        comment="Which agent generated this proposal",
    )
    
    confidence = Column(
        Float,
        nullable=False,
        default=0.0,
        comment="Agent's confidence score (0.0 to 1.0)",
    )
    
    reasoning = Column(
        Text,
        nullable=True,
        comment="Agent's explanation for this proposal",
    )
    
    proposed_action = Column(
        JSONB,
        nullable=False,
        comment="Structured action definition",
    )
    
    additional_metadata = Column(
        JSONB,
        nullable=True,
        default=dict,
        comment="Additional proposal-specific metadata",
    )
    
    # Relationships
    observation = relationship("Observation", backref="proposals")
    
    def __repr__(self) -> str:
        return f"<Proposal(id={self.id}, type={self.proposal_type}, status={self.status}, confidence={self.confidence})>"
